[package]
name = "dwarfs-test"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
colored-diff = "0.2.3"
dwarfs.path = ".."
env_logger = "0.11.8"
tempfile = "3.20.0"
